version: '2.4'

networks:
  effective_mobile:
    driver: bridge
    name: effective_mobile 

services:
  postgres:
    image: postgres:15
    networks:
      - effective_mobile
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "effective_mobile"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "55432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'psql -d effective_mobile -U postgres -c "select 1"']
      interval: 5s
      retries: 10
  psql_migrate:
    image: migrate/migrate
    networks:
      - effective_mobile
    depends_on:
      postgres:
        condition: service_healthy 
    volumes:
      - ./postgres/migration:/postgres/migration
    command: ["-path", "/postgres/migration", "-database",  "postgres://postgres:postgres@postgres:5432/effective_mobile?sslmode=disable", "up"]
